//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4959
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNETViewerComponent.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNETViewerComponent.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap ArrowMenuChoice {
            get {
                object obj = ResourceManager.GetObject("ArrowMenuChoice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ArrowMenuChoice1 {
            get {
                object obj = ResourceManager.GetObject("ArrowMenuChoice1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ArrowMenuSelected {
            get {
                object obj = ResourceManager.GetObject("ArrowMenuSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ColorMenu {
            get {
                object obj = ResourceManager.GetObject("ColorMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ColorMenu1 {
            get {
                object obj = ResourceManager.GetObject("ColorMenu1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dashed1LineMenu2 {
            get {
                object obj = ResourceManager.GetObject("Dashed1LineMenu2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dashed1LineMenuChoice1 {
            get {
                object obj = ResourceManager.GetObject("Dashed1LineMenuChoice1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dashed2LineMenu2 {
            get {
                object obj = ResourceManager.GetObject("Dashed2LineMenu2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dashed2LineMenuChoice1 {
            get {
                object obj = ResourceManager.GetObject("Dashed2LineMenuChoice1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dashed3LineMenu2 {
            get {
                object obj = ResourceManager.GetObject("Dashed3LineMenu2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dashed3LineMenuChoice1 {
            get {
                object obj = ResourceManager.GetObject("Dashed3LineMenuChoice1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dashed4LineMenu2 {
            get {
                object obj = ResourceManager.GetObject("Dashed4LineMenu2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dashed4LineMenuChoice1 {
            get {
                object obj = ResourceManager.GetObject("Dashed4LineMenuChoice1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EllipseMenuChoice {
            get {
                object obj = ResourceManager.GetObject("EllipseMenuChoice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EllipseMenuChoice1 {
            get {
                object obj = ResourceManager.GetObject("EllipseMenuChoice1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EllipseMenuSelected {
            get {
                object obj = ResourceManager.GetObject("EllipseMenuSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EyeCheckbox1 {
            get {
                object obj = ResourceManager.GetObject("EyeCheckbox1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FileOpenMenu1 {
            get {
                object obj = ResourceManager.GetObject("FileOpenMenu1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FileSaveMenu1 {
            get {
                object obj = ResourceManager.GetObject("FileSaveMenu1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FirstPageMenu1 {
            get {
                object obj = ResourceManager.GetObject("FirstPageMenu1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FreeTextMenu2 {
            get {
                object obj = ResourceManager.GetObject("FreeTextMenu2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FreeTextMenuSelected {
            get {
                object obj = ResourceManager.GetObject("FreeTextMenuSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Highlight {
            get {
                object obj = ResourceManager.GetObject("Highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HighlightChoice {
            get {
                object obj = ResourceManager.GetObject("HighlightChoice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ink {
            get {
                object obj = ResourceManager.GetObject("Ink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InkChoice {
            get {
                object obj = ResourceManager.GetObject("InkChoice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LastPageMenu1 {
            get {
                object obj = ResourceManager.GetObject("LastPageMenu1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LineMenuChoice1 {
            get {
                object obj = ResourceManager.GetObject("LineMenuChoice1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LineMenuSelected {
            get {
                object obj = ResourceManager.GetObject("LineMenuSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LineWeight1MenuChoice1 {
            get {
                object obj = ResourceManager.GetObject("LineWeight1MenuChoice1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LineWeight1MenuSelected {
            get {
                object obj = ResourceManager.GetObject("LineWeight1MenuSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LineWeight2MenuChoice1 {
            get {
                object obj = ResourceManager.GetObject("LineWeight2MenuChoice1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LineWeight2MenuSelected {
            get {
                object obj = ResourceManager.GetObject("LineWeight2MenuSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LineWeight3MenuChoice1 {
            get {
                object obj = ResourceManager.GetObject("LineWeight3MenuChoice1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LineWeight3MenuSelected {
            get {
                object obj = ResourceManager.GetObject("LineWeight3MenuSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LineWeight4MenuChoice1 {
            get {
                object obj = ResourceManager.GetObject("LineWeight4MenuChoice1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LineWeight4MenuSelected {
            get {
                object obj = ResourceManager.GetObject("LineWeight4MenuSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Link {
            get {
                object obj = ResourceManager.GetObject("Link", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LinkChoice {
            get {
                object obj = ResourceManager.GetObject("LinkChoice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MarqueeZoomModeMenu1 {
            get {
                object obj = ResourceManager.GetObject("MarqueeZoomModeMenu1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MarqueeZoomModeMenuSelected1 {
            get {
                object obj = ResourceManager.GetObject("MarqueeZoomModeMenuSelected1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NextPageMenu1 {
            get {
                object obj = ResourceManager.GetObject("NextPageMenu1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PolygonMenu {
            get {
                object obj = ResourceManager.GetObject("PolygonMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PolygonMenuChoice {
            get {
                object obj = ResourceManager.GetObject("PolygonMenuChoice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PolygonMenuSelected {
            get {
                object obj = ResourceManager.GetObject("PolygonMenuSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PolyLineMenu {
            get {
                object obj = ResourceManager.GetObject("PolyLineMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PolyLineMenu1 {
            get {
                object obj = ResourceManager.GetObject("PolyLineMenu1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PolyLineMenuSelected {
            get {
                object obj = ResourceManager.GetObject("PolyLineMenuSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PreviousPageMenu1 {
            get {
                object obj = ResourceManager.GetObject("PreviousPageMenu1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PrintMenu1 {
            get {
                object obj = ResourceManager.GetObject("PrintMenu1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PrintMenu2 {
            get {
                object obj = ResourceManager.GetObject("PrintMenu2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RectangelMenu {
            get {
                object obj = ResourceManager.GetObject("RectangelMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RectangleMenuChoice {
            get {
                object obj = ResourceManager.GetObject("RectangleMenuChoice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RectangleMenuChoice1 {
            get {
                object obj = ResourceManager.GetObject("RectangleMenuChoice1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RectangleMenuSelected {
            get {
                object obj = ResourceManager.GetObject("RectangleMenuSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SelectModeMenu1 {
            get {
                object obj = ResourceManager.GetObject("SelectModeMenu1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SelectModeSelected {
            get {
                object obj = ResourceManager.GetObject("SelectModeSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SolidLineMenuChoice1 {
            get {
                object obj = ResourceManager.GetObject("SolidLineMenuChoice1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SolidLineMenuSelected {
            get {
                object obj = ResourceManager.GetObject("SolidLineMenuSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SolidLineMenuSelected1 {
            get {
                object obj = ResourceManager.GetObject("SolidLineMenuSelected1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SolidLineMenuSelected2 {
            get {
                object obj = ResourceManager.GetObject("SolidLineMenuSelected2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Transparency {
            get {
                object obj = ResourceManager.GetObject("Transparency", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap transparencySymbol100x100 {
            get {
                object obj = ResourceManager.GetObject("transparencySymbol100x100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap transparencySymbol12x12 {
            get {
                object obj = ResourceManager.GetObject("transparencySymbol12x12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Underline {
            get {
                object obj = ResourceManager.GetObject("Underline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UnderlineChoice {
            get {
                object obj = ResourceManager.GetObject("UnderlineChoice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ZoomDecreaseMenu1 {
            get {
                object obj = ResourceManager.GetObject("ZoomDecreaseMenu1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ZoomIncreaseMenu1 {
            get {
                object obj = ResourceManager.GetObject("ZoomIncreaseMenu1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ZoomModeMenu1 {
            get {
                object obj = ResourceManager.GetObject("ZoomModeMenu1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ZoomModeMenuSelected1 {
            get {
                object obj = ResourceManager.GetObject("ZoomModeMenuSelected1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
